### ISSUE TITLE
跟市面已经软件对比差异

### ISSUE THREAD

**Issue by C16103112** [Taogram/taobi#8]
我代码中使用
 const taobi = new TheArtOfBecomingInvisible(new Date(), null, 1, null, {
      elements: 1,
    });
    得到的是
![af5ac27da9ccd3c099d703df24f68f7](https://github.com/user-attachments/assets/9f6da030-6f90-4a2d-a799-724f758c6c3d)
我再其他相关软件得到的是
![a19d1a9cc44d336ce95224288905d05](https://github.com/user-attachments/assets/755ae662-8189-4c79-b881-622750b8c575)
八门的顺序不一样这是因为我传的参数有问题吗

**Comment by laxnogithub** [comment]
不是。。我查了下发现我的拆补算法写错了，把日干写成了时干，等下修复一下

**Comment by C16103112** [comment]
> 不是。。我查了下发现我的拆补算法写错了，把日干写成了时干，等下修复一下

茅山是不是也有相同的问题

**Comment by C16103112** [comment]
![0fd072c216f2a9b343a085de9f7235dc](https://github.com/user-attachments/assets/40d80f44-2ccb-41df-8c68-912d81951471)
![af5ac27da9ccd3c099d703df24f68f7](https://github.com/user-attachments/assets/b6caabfa-d02d-40f8-a7c7-b1ce67b6db9b)

**Comment by C16103112** [comment]
![0fd072c216f2a9b343a085de9f7235dc](https://github.com/user-attachments/assets/bc5b466a-888b-4fae-acdc-943e59471fde)
![af5ac27da9ccd3c099d703df24f68f7](https://github.com/user-attachments/assets/4cc3934d-ff91-42db-9f72-80c7eece7b7d)

**Comment by laxnogithub** [comment]
恩。。是的，也修复了
